# netlify.toml

[build]
  command = "npm run build"
  publish = "public"
  functions = "lambda"

[context.develop] # 'develop' is a branch name
  VARIABLE = "value"
  NODE_ENV = "staging"
  # command = "echo 'develop'"
#   NODE_ENV = "staging"
