# netlify.toml

[build]
  command = "npm run build"
  publish = "public"
  functions = "lambda"
  environment = { PAYPAL_SANDBOX_CLIENT_ID = 'AVQRQZrhx5INZ0hvHyFoj6m_vmp94wl8q4mEIcQ6fbuVdjOesWdUEy-V2fa4peZLtXfzKC5-k9j1mlks', PAYPAL_SECRET = 'ECWnpEE_GmHvAE1eobMrxkd6-u9ugeabUhENE_eAOHR_Kx6m3bYo2ScCNK6C76nrqvA3BFza_VitAm2k', GMAIL_EMAIL = 'lessonsabroad@gmail.com', GMAIL_PASSWORD = 'oTKPORsIoua4', FIREBASE_FUNCTIONS_KEY = 'secret333', DISCOUNT_CODE = '123' }
