backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: img

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/contact/contact.md"
        label: "Contact"
        name: "contact"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "contact-page"}
          - {label: "Path", name: "path", widget: "hidden", default: "/contact"}
          - {label: "Title", name: "title", widget: "string"}
          - label: "Photographic evidence"
            name: "evidenceImage"
            widget: "custompathimage"
            customMediaPath: "../../../static/img/"
            rawMediaPath: "https://raw.githubusercontent.com/JonathanHalpern/year-of-the-challenge/master/static/img/"
            required: true
          - {label: "Email address for contact messages", name: "contactEmail", widget: "string"}
          - {label: "Message shown after contact message sent", name: "onEmailSendMessage", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}

      - file: "src/pages/about/about.md"
        label: "About"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Path", name: "path", widget: "hidden", default: "/about"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/location/location.md"
        label: "Location"
        name: "location"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "location-page"}
          - {label: "Path", name: "path", widget: "hidden", default: "/location"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
          - label: "Map Locations"
            name: "mapLocations"
            widget: "list"
            fields:
              - {label: "Legend", name: "legend", widget: "string"}
              - {label: "Address", name: "address", widget: "string"}
          - label: "Starting zoom level"
            name: "defaultZoom"
            widget: "number"
            default: 18
            valueType: "int"
            min: 1
            max: 20

      - file: "src/pages/book/book.md"
        label: "Book"
        name: "book"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "book-page"}
          - {label: "Path", name: "path", widget: "hidden", default: "/book"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Email address for booking alerts", name: "bookingAlertEmail", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
          - label: "Time Slots"
            name: "timeSlots"
            widget: "list"
            fields:
              - {label: "Start Time", name: "startTime", widget: "time"}
              - {label: "End Time", name: "endTime", widget: "time"}
              - label: "Price (£)"
                name: "price"
                widget: "number"
                valueType: "int"
                min: 0
