backend:
  name: git-gateway
  branch: master

collections:

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/contact/contact.md"
        label: "Contact"
        name: "contact"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "contact-page"}
          - {label: "Path", name: "path", widget: "hidden", default: "/contact"}
          - {label: "Body", name: "body", widget: "markdown"}
          - {label: "Title", name: "title", widget: "string"}
